version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.1
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-Admin123}
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:${ELASTIC_PASSWORD:-Admin123} -s -f http://localhost:9200/_cluster/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Setup container to create Kibana user
  elasticsearch-setup:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic
    command: >
      sh -c "
        echo 'Creating kibana_system user...'
        curl -u elastic:${ELASTIC_PASSWORD:-Admin123} -X POST 'http://elasticsearch:9200/_security/user/kibana_system/_password' -H 'Content-Type: application/json' -d '{\"password\":\"${KIBANA_PASSWORD:-KibanaPass123}\"}'
        echo 'Kibana user password set successfully'
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD:-KibanaPass123}
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=kibana
      - LOGGING_ROOT_LEVEL=warn
      - xpack.security.enabled=true
      - xpack.encryptedSavedObjects.encryptionKey=a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-setup:
        condition: service_completed_successfully
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:5601/api/status >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge